# Ultralytics YOLO 🚀, AGPL-3.0 license

path: training/dataset # dataset root dir
train: images/train/ # train images (relative to 'path') 
val: images/val/ # val images (relative to 'path')

# Classes
names:
  0: player
  1: referee
  2: ball
