[server]
maxUploadSize = 3500
maxMessageSize = 500

[theme]
# Primary color.
primaryColor = "#cf1507"

# Background color.
backgroundColor = "#132e13"

# Secondary background.
secondaryBackgroundColor = "#000000"

# Text color.
textColor = "#FFFFFF"

# Font family
font = "monospace"
